Finish Version of the Mobile View Portfolio Project branch  PULL REQUEST #1
efmomoh/Mobile_View-Portforlio pull request #2
Opened 2023-03-29 10:47 UTC by efmomoh

This project is a finished version of the HTML-CSS component of the mobile view version. 
It is built from Figma designs of Template 1-mobile-main version.

Also, it is built on the following:
- HTML
- CSS
-  Figma template
- And tests with Linters to ensure no typos and syntax errors are found.

2023-03-29 11:19 UTC, AlphaNtihinduka requested changes
## Hi @efmomoh 🙋‍♂️
Good job working on your mobile version of portifolio. You have done the design to the best expectation and incredibly well. 👏  

You still need to implement few on the project but you are almost there!!! 🚶: 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

# Required Changes :recycle: 
- Kindly consider the inline review comments.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-03-29 11:19 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] Let's try as much as possible to ensure that the remaining `li` match the Figma design. I suggest you ensure that the color and size are changed to match the Figma design. This will make our portfolio more professional ☺️.

2023-03-29 11:19 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] Please make sure that the color of the stacks is changed to match the Figma design. This helps to balance the colors of the portfolio and make it more professional ☺️. Your current color is `#551A8B` instead of `#6070FF`

2023-03-29 11:19 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] Please try as much as possible to stick to the Figma template design.  We need to ensure that our button matches the Figma design in terms of hover, enabled, disabled, and pressed. This will make our buttons more interactive and userfriendly ☺️.

Figma design ☺️
![image](https://user-images.githubusercontent.com/99394374/228514763-d9571f63-9378-4a6b-9124-62404852e4fb.png)

2023-03-29 11:19 UTC, AlphaNtihinduka commented on index.html
> +<div class="work-sections">
- [ ] The container of the section is a section tag. This improves the accessibility of the portfolio. In addition, for semantic purposes the sections should be contained in `section` tag.

2023-03-29 11:19 UTC, AlphaNtihinduka commented on index.html
> +<div class="about-section">
- [ ] The container of the section is a section tag. This improves the accessibility of the portfolio. In addition, for semantic purposes, the sections should be contained in the `section` tag.

2023-03-29 11:19 UTC, AlphaNtihinduka commented on index.html
> +  </div>
- [ ] Kindly let's ensure that there is only one `h1` tag on our page. This is to ensure the accessibility of the portfolio. Therefore I suggest that all the `h1` headings that are not the main headings of the page are changed to `h2-h6` instead.

2023-03-29 11:19 UTC, AlphaNtihinduka commented on index.html
> +      <h1>Stories</h1>
- [ ] Kindly let's ensure that there is only one `h1` tag on our page. This is to ensure the accessibility of the portfolio. Therefore I suggest that all the `h1` headings that are not the main headings of the page are changed to `h2-h6` instead.

2023-03-29 11:19 UTC, AlphaNtihinduka commented on index.html
> +      <div class="canopy-section">
- [ ] Kindly let's ensure that there is only one `h1` tag on our page. This is to ensure the accessibility of the portfolio. Therefore I suggest that all the `h1` headings that are not the main headings of the page are changed to `h2-h6` instead.

2023-03-29 13:11 UTC, efmomoh commented on index.html
> +  </div>
Thank you for the feedback!
Is the set-up page header (h1) count in this process too? or it counts only for the work sections?

2023-03-29 18:12 UTC, efmomoh commented on style.css
> +}
So which color is required of my project? Please help!

2023-03-29 18:21 UTC, efmomoh commented on style.css
> +}
Is it optional to use any button of your choice?

2023-03-30 00:28 UTC, efmomoh commented
This project has been updated by removing repeated headers and modified.

2023-03-30 01:39 UTC, mahbubul14 requested changes
Hi @efmomoh,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-30 01:39 UTC, mahbubul14 commented on index.html
> +    </div>
- [ ] As the previous reviewer suggested, kindly follow the button styling: Active, Hover, and Pressed (see design). Also, The section should use the font and colors (background and font) defined for the template. Kindly do the change for all the buttons on the page. :+1: 

![btn](https://user-images.githubusercontent.com/70483835/228705020-fc2120d7-938f-4784-a80c-eddd755cb3eb.png)

2023-03-30 01:39 UTC, mahbubul14 commented on index.html
> +      </ul>
- [ ] As the previous reviewer suggested, Please make sure that the color of the stacks is changed to match the Figma design. This helps to balance the colors of the portfolio and make it more professional and relaxed. the color should be `#6070FF` :+1:

2023-03-30 08:38 UTC, efmomoh commented on index.html
> +    </div>
The buttons in the Figma design do not have such styling buttons or types. It does not illustrate whether it is an enabled, hover, pressed, or disabled button. @mahbubul14

2023-03-30 19:17 UTC, huseyinbiyik approved these changes
Hi @efmomoh  

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions
- Please notice that the background color and the colors for the works cards, about myself sections, are different. The background is #F7F7F9 and cards are #FFFFFFF Kindly remove the border around the cards and about myself section.
<img width="407" alt="Screenshot 2023-03-30 at 10 10 00 PM" src="https://user-images.githubusercontent.com/25887253/228940291-9976459f-5bb7-454c-880d-c4d554e5b393.png">

<img width="651" alt="Screenshot 2023-03-30 at 10 12 11 PM" src="https://user-images.githubusercontent.com/25887253/228940303-a91d5d3a-ddc2-455c-8ad3-410b673e632e.png">

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 19:17 UTC, huseyinbiyik commented on style.css
> +  color: #6070FF;
[OPTIONAL] Please don't leave any uncommented code in your codebase. In this way you can keep your codebase neat, organized and professional 👍

2023-03-31 08:09 UTC, efmomoh commented on style.css
> +  color: #6070FF;
Ok, thank you for the feedback. 
@huseyinbiyik Do you mean that there are no borders around the pages?

2023-03-31 09:05 UTC, merged

2023-03-31 09:26 UTC, huseyinbiyik commented on style.css
> +  color: #6070FF;
Hey @efmomoh, sorry, there was a border only for cards. Not for About Myself and Hero section 👍  
<img width="697" alt="Screenshot 2023-03-31 at 12 21 13 PM" src="https://user-images.githubusercontent.com/25887253/229081711-d5db533c-c4ae-4c21-8cc9-f902f7847860.png">
<img width="842" alt="Screenshot 2023-03-31 at 12 22 01 PM" src="https://user-images.githubusercontent.com/25887253/229081726-15051589-a0ec-4f3a-bbc6-24e9321c4e1c.png">
<img width="917" alt="Screenshot 2023-03-31 at 12 23 09 PM" src="https://user-images.githubusercontent.com/25887253/229081733-cfc7ccdf-6364-4669-9985-a506bf672e02.png">