Create desktop view
efmomoh/Mobile_View-Portforlio pull request #4
Opened 2023-04-07 21:44 UTC by efmomoh

This is the desktop version of my portfolio project. 
it was built upon HTML-CSS-media queries.

2023-04-07 23:59 UTC, Kossi-stack requested changes
## Hi @efmomoh,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-07 23:59 UTC, Kossi-stack commented on index.html
> +              <button class="button" type="button">See Project</button>
- [ ] Kindly fix the border radius given to the button

2023-04-07 23:59 UTC, Kossi-stack commented on index.html
> +    <section class="about-section" id="my-page">
- [ ] Kindly align the about me session well by using padding-left.
- [ ] Your Design
<img width="1440" alt="Screenshot 2023-04-07 at 16 54 00" src="https://user-images.githubusercontent.com/81444338/230693877-e2ae4ee1-d2ba-49a9-a9a7-5be5ad9b606e.png">

Figma  Design
<img width="1273" alt="Screenshot 2023-04-07 at 16 56 26" src="https://user-images.githubusercontent.com/81444338/230693959-16487830-eb7e-4468-965d-80e8bfdef8ef.png">

2023-04-08 06:13 UTC, shella12 approved these changes
Hi @efmomoh , 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 
- Great design implementation 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-08 06:13 UTC, shella12 commented on style.css
> +
- [ ] [OPTIONAL] Great job on your portfolio it looks great almost identical to the figma, however I noticed some blank space after the contact form in desktop version. I would highly suggest you to fix it as it makes your design look sloppy.

<img width="1498" alt="Screenshot 2023-04-08 at 11 08 30 AM" src="https://user-images.githubusercontent.com/44798044/230706445-a9824783-a9da-49cb-b402-0b8ec6ea183d.png">

2023-04-08 11:30 UTC, efmomoh commented on style.css
> +
@shella12 thanks a lot for the feedback. I will implement it.

2023-04-08 11:31 UTC, efmomoh commented on index.html
> +    <section class="about-section" id="my-page">
@Kossi-stack  thanks for the feedback. I will make those adjustments.

2023-04-08 11:45 UTC, merged